"""Initial schema

Revision ID: 6272d7ba71f6
Revises: 
Create Date: 2026-05-26 10:24:48.966011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6272d7ba71f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites')
    op.drop_table('audit_logs')
    op.drop_table('room_unavailability')
    op.drop_table('reviews')
    op.drop_index('idx_bookings_status', table_name='bookings')
    op.drop_index('idx_bookings_user_id', table_name='bookings')
    op.create_index('ix_bookings_is_deleted', 'bookings', ['is_deleted'], unique=False)
    op.create_index('ix_bookings_room_id', 'bookings', ['room_id'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_time_range', 'bookings', ['room_id', 'start_time', 'end_time'], unique=False)
    op.create_index('ix_bookings_user_active', 'bookings', ['user_id', 'is_deleted', 'status'], unique=False)
    op.create_index('ix_bookings_user_id', 'bookings', ['user_id'], unique=False)
    op.drop_column('bookings', 'duration_minutes')
    op.alter_column('coworking_spaces', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('coworking_spaces', 'images')
    op.drop_column('coworking_spaces', 'email')
    op.drop_column('coworking_spaces', 'amenities')
    op.drop_column('coworking_spaces', 'phone')
    op.drop_column('coworking_spaces', 'website')
    op.drop_column('coworking_spaces', 'operating_hours')
    op.drop_column('coworking_spaces', 'description')
    op.drop_column('coworking_spaces', 'country')
    op.drop_column('coworking_spaces', 'timezone')
    op.alter_column('rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('rooms_coworking_space_id_name_key', 'rooms', type_='unique')
    op.drop_column('rooms', 'images')
    op.drop_column('rooms', 'amenities')
    op.drop_column('rooms', 'floor')
    op.drop_column('rooms', 'room_number')
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'hourly_rate')
    op.drop_column('rooms', 'square_meters')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_is_deleted', 'users', ['is_deleted'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_is_deleted', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.add_column('rooms', sa.Column('square_meters', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('hourly_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('room_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('floor', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.create_unique_constraint('rooms_coworking_space_id_name_key', 'rooms', ['coworking_space_id', 'name'])
    op.alter_column('rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('coworking_spaces', sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=True))
    op.add_column('coworking_spaces', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('coworking_spaces', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('coworking_spaces', sa.Column('operating_hours', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"friday": {"open": "09:00", "close": "18:00"}, "monday": {"open": "09:00", "close": "18:00"}, "sunday": {"open": null, "close": null}, "tuesday": {"open": "09:00", "close": "18:00"}, "saturday": {"open": null, "close": null}, "thursday": {"open": "09:00", "close": "18:00"}, "wednesday": {"open": "09:00", "close": "18:00"}}\'::jsonb'), autoincrement=False, nullable=False))
    op.add_column('coworking_spaces', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('coworking_spaces', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('coworking_spaces', sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('coworking_spaces', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('coworking_spaces', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.alter_column('coworking_spaces', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('bookings', sa.Column('duration_minutes', sa.INTEGER(), sa.Computed('(EXTRACT(epoch FROM (end_time - start_time)) / (60)::numeric)', persisted=True), autoincrement=False, nullable=True))
    op.drop_index('ix_bookings_user_id', table_name='bookings')
    op.drop_index('ix_bookings_user_active', table_name='bookings')
    op.drop_index('ix_bookings_time_range', table_name='bookings')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_room_id', table_name='bookings')
    op.drop_index('ix_bookings_is_deleted', table_name='bookings')
    op.create_index('idx_bookings_user_id', 'bookings', ['user_id'], unique=False)
    op.create_index('idx_bookings_status', 'bookings', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('coworking_space_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('(rating >= 1) AND (rating <= 5)', name='reviews_rating_check'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='reviews_booking_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coworking_space_id'], ['coworking_spaces.id'], name='reviews_coworking_space_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey'),
    sa.UniqueConstraint('user_id', 'coworking_space_id', 'booking_id', name='reviews_user_id_coworking_space_id_booking_id_key')
    )
    op.create_table('room_unavailability',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('room_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_recurring', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('recurring_pattern', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('end_time > start_time', name='room_unavailability_check'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='room_unavailability_room_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='room_unavailability_pkey')
    )
    op.create_table('audit_logs',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_table('user_favorites',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('coworking_space_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coworking_space_id'], ['coworking_spaces.id'], name='user_favorites_coworking_space_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_favorites_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'coworking_space_id', name='user_favorites_pkey')
    )
    # ### end Alembic commands ###